### ISSUE TITLE
TypeError when the range extends beyond the number of columns available

### ISSUE THREAD

**Issue by dennisobrien** [RobinGertenbach/Reshape#20]
When using `BlanksBehavior=0` and passing a range that includes some blank columns, I get an error.

For example, I have data in a tab 'Some_Sheet with 11 columns, and I call `MELT` like this:
```
MELT(Some_Sheet!A1:Z, Some_Sheet!A1, "name", "value", 0)
```
I get this error:
```
TypeError: Cannot read property "11" from undefined. (line 115).
```

I think in the case of the range extending beyond the number of available columns, the reference `a[col]` is null and a TypeError thrown.
```
/**
 * Checks if a column is empty
 */
function columnIsEmpty(a, col) {
  for (var row in a[0]) {
    if (a[row][col] !== "" && a[row][col] !== undefined) {
      return false;
    }
  }
  return true;
}

I have a simple fix that I'll add as a PR.

cheers,
Dennis


```

**Comment by rgertenbach** [comment]
Oh, wow. Thanks for highlighting this, I only ever tested extra columns and extra rows but not both.
If you do have a fix already I'll greatly appreciate you sharing it.
Thank you

**Comment by rgertenbach** [comment]
Thanks Dennis!
