### ISSUE TITLE
Problem with specifying the ID variable names

### ISSUE THREAD

**Issue by moleps** [RobinGertenbach/Reshape#22]
Thanks for the reshape package. Really helpful. Might be worth to consider publishing it for easier access. I stunmbled across an issue in specifying the ID variables. Works beautiful when I specify the cells, but not when I use the column name.

Please see [sheet link](https://docs.google.com/spreadsheets/d/165od08iXSbNfAFZAaOQuLWZuW51WUYev4g6ArzbptnE/edit?usp=sharing) ouput when I use cells (cell H1) and names (cell M1).

**Comment by rgertenbach** [comment]
Thank you.
In this case the issue is that the time column in the source table has a space at the end, you could either remove it in the source table or use `{"topic";"time "}`.

I've been trying to publish it but needed to supply stuff I didn't have handy at the time, I hope I can be bothered to actually publish it at some point

**Comment by moleps** [comment]
Thanks for the feedback and I feel very stupid. However, after both trying the added space and removing the space I still get the same result. Were you able to reproduce the reshaped table using variable names?

Best,

M


11. okt. 2019 kl. 14:37 skrev Robin Gertenbach <notifications@github.com>:

Closed #22 <https://github.com/rgertenbach/Reshape/issues/22>.

**Comment by rgertenbach** [comment]
Ah, sorry, try using a `,` instead of a `;`.
`;` Makes a new row

**Comment by rgertenbach** [comment]
Also you may need to delete, <enter>, reinsert the formula To force Sheets to update

**Comment by moleps** [comment]
OK-- The , instead of the ; worked wonders. But still specifying the variable names changed the formatting of the time column (from 9:00:00 AM to 12/30/1899 (9:00:00))



11. okt. 2019 kl. 16:11 skrev Robin Gertenbach <notifications@github.com>:

Also you may need to delete, , reinsert the formula To force Sheets to update

**Comment by rgertenbach** [comment]
Not sure why that is with the referenced range but not the manual one but
it's just a matter of changing the format of the cells
